#:kivy 1.0.9

<RootWidget>:
    orientation: 'vertical'
    FileChooserIconView:
        id: filechooser
        dirselect: True
        size_hint_y: 0.7
    BoxLayout:
        size_hint_y: 0.1
        orientation: 'horizontal'
        Button:
            text: "Select"
            size_hint_x: 0.2
            on_release: root.select()
    Label:
        size_hint_y: 0.2
        text: root.status_text